aozora_bunko_review/urls.py
from django.contrib import admin
from django.urls import path
from django.urls.conf import include


urlpatterns = [
    path("admin/", admin.site.urls),
    path("", include("reviews.urls")),
    path("old_account/", include("user_account.urls")),
    path("accounts/", include("allauth.urls")),
]

reviews/urls.py
from django.urls import path
from .views import IndexView, SearchResultsView, AboutView, BookDetailView, DetailSearchView, DetailSearchResultView, \
    ReviewCreateView, ReviewUpdateView

urlpatterns = [
    path('', IndexView.as_view(), name='index'),
    path('search/', SearchResultsView.as_view(), name='search_result'),
    path('about/', AboutView.as_view(), name='about'),
    path('books/<int:pk>/', BookDetailView.as_view(), name='book_detail'),
    path('books/<int:book_id>/review/new/', ReviewCreateView.as_view(), name='review_create'),
    path('books/<int:book_id>/review/<int:review_id>/', ReviewUpdateView.as_view(), name='review_edit'),

    path('detail_search/', DetailSearchView.as_view(), name='detail_search'),
    path('detail_search_results/', DetailSearchResultView.as_view(), name='detail_search_results'),

]

reviews/models.py
from django.contrib.auth.models import User
from django.db import models
from django.contrib import auth
from tailwind.validate import ValidationError


class Author(models.Model):
    person_id = models.IntegerField(primary_key=True)
    first_name = models.CharField(max_length=100, null=True, blank=True)
    last_name = models.CharField(max_length=100)
    first_name_reading = models.CharField(max_length=100, null=True, blank=True)
    last_name_reading = models.CharField(max_length=100)
    first_name_sorting = models.CharField(max_length=100, null=True, blank=True)
    last_name_sorting = models.CharField(max_length=100)
    full_name = models.CharField(max_length=100, null=True, blank=True)
    full_name_reading = models.CharField(max_length=100, null=True, blank=True)
    wikipedia_link = models.URLField(max_length=200, null=True, blank=True)

    def save(self, *args, **kwargs):
        self.full_name = f'{self.last_name}{self.first_name or ""}'
        self.full_name_reading = f'{self.last_name_reading}{self.first_name_reading or ""}'
        super().save(*args, **kwargs)

    def __str__(self):
        return f'{self.full_name}'

    
class NDC_Classification(models.Model):
    ndc_code = models.CharField(max_length=10, unique=True)
    genre = models.CharField(max_length=500, null=True, blank=True)

    def __str__(self):
        return self.ndc_code


class BaseTextInfo(models.Model):
    base_text_name = models.CharField(max_length=500)
    base_text_publisher = models.CharField(max_length=256, null=True, blank=True)
    base_text_publish_year = models.CharField(max_length=100, null=True, blank=True)
    parent_text_name = models.CharField(max_length=500, null=True, blank=True)
    parent_text_publisher = models.CharField(max_length=256, null=True, blank=True)
    parent_text_publish_year = models.CharField(max_length=100, null=True, blank=True)

    def __str__(self):
        return self.base_text_name

class Work(models.Model):
    title = models.CharField(max_length=256)
    title_reading = models.CharField(max_length=256)
    title_sorting = models.CharField(max_length=256, null=True, blank=True)
    sub_title = models.CharField(max_length=256, null=True, blank=True)
    sub_title_reading = models.CharField(max_length=256, null=True, blank=True)
    original_title = models.CharField(max_length=256, null=True, blank=True)
    classification_number = models.CharField(max_length=50, null=True, blank=True)
    character_usage = models.CharField(max_length=50)
    copyright_flag = models.BooleanField(default=False)
    release_date = models.DateField(null=True, blank=True)
    last_updated = models.DateField(null=True, blank=True)
    book_card_url = models.URLField(max_length=200)
    role_flag = models.CharField(max_length=50, default='著者')  # 役割フラグを追加
    authors = models.ManyToManyField(Author,related_name='works', blank=True)
    translator = models.ForeignKey(Author, on_delete=models.SET_NULL, null=True, blank=True,
                                   related_name='translated_works')
    editor = models.ForeignKey(Author, on_delete=models.SET_NULL, null=True, blank=True, related_name='edited_works')
    other_role = models.ForeignKey(Author, on_delete=models.SET_NULL, null=True, blank=True,
                                   related_name='other_role_works')
    text_file_url = models.URLField(max_length=200, null=True, blank=True)
    html_file_url = models.URLField(max_length=200, null=True, blank=True)
    genre_info1 = models.ForeignKey(NDC_Classification, null=True, blank=True, on_delete=models.SET_NULL,
                                    related_name='primary_works')
    genre_info2 = models.ForeignKey(NDC_Classification, null=True, blank=True, on_delete=models.SET_NULL,
                                    related_name='secondary_works')
    base_text_info = models.ForeignKey(BaseTextInfo, null=True, blank=True, on_delete=models.SET_NULL, related_name='base_text_info')

    class Meta:
        unique_together = (('title', 'sub_title', 'original_title', 'book_card_url'),)
    def __str__(self):
        return self.title


class FirstPublication(models.Model):
    work = models.OneToOneField(Work, related_name='first_publication', on_delete=models.CASCADE)
    publication_info = models.TextField()

    def __str__(self):
        return self.publication_info[:15]


def validate_rating(value):
    if value < 1 or value > 5:
        raise ValidationError("It must be between 1 and 5.")


class Review(models.Model):
    title = models.CharField(max_length=255)
    rating = models.IntegerField(validators=[validate_rating])
    content = models.TextField()
    date_created = models.DateTimeField(auto_now_add=True)
    date_edited = models.DateTimeField(null=True, blank=True)
    is_spoiler = models.BooleanField(default=False)
    creator = models.ForeignKey(
        auth.get_user_model(),  on_delete=models.CASCADE, related_name="review_user"
    )
    book = models.ForeignKey(
        Work, on_delete=models.CASCADE, related_name="review_book"
    )

reviews/forms.py
from django import forms

from reviews.models import Review


class DetailSearchForm(forms.Form):
    title = forms.CharField(required=False, label='書籍名')
    title_reading = forms.CharField(required=False, label='書籍名（読み）')
    author_last_name = forms.CharField(required=False, label='著者の姓')
    author_first_name = forms.CharField(required=False, label='著者の名')
    author_last_name_reading = forms.CharField(required=False, label='著者の姓（読み）')
    author_first_name_reading = forms.CharField(required=False, label='著者の名（読み）')
    translator_last_name = forms.CharField(required=False, label='翻訳者の姓')
    translator_first_name = forms.CharField(required=False, label='翻訳者の名')
    translator_last_name_reading = forms.CharField(required=False, label='翻訳者の姓（読み）')
    translator_first_name_reading = forms.CharField(required=False, label='翻訳者の名（読み）')
    character_usage = forms.ChoiceField(required=False, choices=[
        ('新字旧仮名', '新字旧仮名'),
        ('旧字旧仮名', '旧字旧仮名'),
        ('新字新仮名', '新字新仮名'),
    ], label='仮名遣い')
    is_children_book = forms.BooleanField(required=False, label='児童書')



class ReviewForm(forms.ModelForm):
    class Meta:
        model = Review
        fields = ['title', 'rating', 'content', 'is_spoiler']
        labels = {
            'title': 'タイトル',
            'rating': '1〜５で評価',
            'content': 'レビュー内容',
            'is_spoiler': 'ネタバレを含む'
        }
        widgets = {
            'rating': forms.Select(choices=[(i, i) for i in range(1, 6)]),
        }

reviews/views.py
from django.utils import timezone
from allauth.account.views import ConfirmEmailView
from django.contrib.auth.mixins import LoginRequiredMixin, UserPassesTestMixin
from django.shortcuts import render, redirect
from django.urls import reverse
from django.views.generic import TemplateView, DetailView, ListView, FormView, CreateView, UpdateView
from django_filters.views import FilterView
from django.core.paginator import Paginator
from django.shortcuts import render, get_object_or_404
from django.contrib import messages
from user_account.models import ReviewHistory
from reviews.filters import WorkFilter, DetailSearchFilter
from reviews.forms import DetailSearchForm, ReviewForm
from reviews.models import Work, Review
from django.utils.html import escape
from reviews.utils import SearchHistoryManager, keep_latest_page_param


class IndexView(TemplateView):
    template_name = 'index.html'

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        show_success_dialog = self.request.GET.get('new_user') == 'true'
        context['show_success_dialog'] = show_success_dialog

        return context


class SearchResultsView(FilterView):
    model = Work
    template_name = 'search_result.html'
    context_object_name = 'works'
    filterset_class = WorkFilter
    paginate_by = 10
    search_history_manager = SearchHistoryManager()

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        works = context['page_obj']
        for work in works:
            work.authors_count = work.authors.count()
            if work.authors_count == 1:
                work.single_author = work.authors.first()

        search_query = keep_latest_page_param(self.request.GET.urlencode())
        context['search_query'] = escape(search_query)

        # 'page' パラメータがない場合のみ検索履歴に保存
        self.search_history_manager.save_search_history(self.request.user, self.request)

        return context



class AboutView(TemplateView):
    template_name = 'about.html'


class BookDetailView(DetailView):
    model = Work
    template_name = 'book_detail.html'
    context_object_name = 'work'

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        work = self.get_object()

        authors = work.authors.all()

        authors_wikipedia_links = []

        context['authors'] = work.authors.all()
        context['translator'] = work.translator
        context['editor'] = work.editor
        context['other_role'] = work.other_role
        context['first_publication_info'] = work.first_publication.publication_info if hasattr(work,'first_publication') else None
        context['base_text_info'] = work.base_text_info if hasattr(work, 'base_text_info') else None
        context['genre_info1'] = work.genre_info1.genre if work.genre_info1 else None
        context['genre_info2'] = work.genre_info2.genre if work.genre_info2 else None
        context['authors_count'] = work.authors.count()
        if context['authors_count'] == 1:
            context['single_author'] = context['authors'].first()
        else:
            context['single_author'] = None

        context['page'] = self.request.GET.get('page')

        search_query = keep_latest_page_param(self.request.GET.urlencode())
        context['search_query'] = escape(search_query)
        context['reviews'] = work.review_book.all()
        return context


class DetailSearchView(FormView):
    template_name = 'detail_search.html'
    form_class = DetailSearchForm

    def form_valid(self, form):
        query_params = form.cleaned_data
        query_params['q'] = 'detail_search'  # クエリにqパラメータを追加
        query_string = "&".join([f"{key}={value}" for key, value in query_params.items() if value])
        return redirect(f"{reverse('detail_search_results')}?{query_string}")


class DetailSearchResultView(FilterView):
    model = Work
    template_name = 'detail_search_result.html'
    context_object_name = 'works'
    filterset_class = DetailSearchFilter
    paginate_by = 10
    search_history_manager = SearchHistoryManager()

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        works = context['page_obj']
        for work in works:
            work.authors_count = work.authors.count()
            if work.authors_count == 1:
                work.single_author = work.authors.first()

        context['search_query'] = keep_latest_page_param(self.request.GET.urlencode())

        # 'page' パラメータがない場合のみ検索履歴に保存
        self.search_history_manager.save_search_history(self.request.user, self.request)

        return context

class ReviewCreateView(LoginRequiredMixin, CreateView):
    model = Review
    form_class = ReviewForm
    template_name = 'review_form.html'

    def get_form(self, form_class=None):
        form = super().get_form(form_class)
        book_id = self.kwargs.get('book_id')
        book = get_object_or_404(Work, pk=book_id)
        form.instance.book = book
        return form

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        book_id = self.kwargs.get('book_id')
        context["book_id"] = book_id
        search_query = keep_latest_page_param(self.request.GET.urlencode())
        context['search_query'] = escape(search_query)

        return context

    def get_success_url(self):
        search_query = escape(self.request.GET.urlencode())
        if search_query:
            return f"{reverse('book_detail', kwargs={'pk': self.kwargs.get('book_id')})}?{search_query}"
        return reverse('book_detail', kwargs={'pk': self.kwargs.get('book_id')})

    def form_valid(self, form):
        review = form.save(commit=False)
        book_id = self.kwargs.get('book_id')
        review.book = get_object_or_404(Work, pk=book_id)
        review.creator = self.request.user
        review.save()
        messages.success(self.request, 'レビューが投稿されました。')
        form.instance.creator = self.request.user

        ReviewHistory.objects.create(
            user = self.request.user,
            review=review,
            review_url=reverse('book_detail', kwargs={'pk':self.kwargs.get('book_id')}),
        )

        return super().form_valid(form)


class ReviewUpdateView(UserPassesTestMixin, UpdateView):
    model = Review
    template_name = 'review_form.html'
    form_class = ReviewForm


    def get_object(self, queryset=None):
        review_id = self.kwargs.get('review_id')
        return get_object_or_404(Review, id=review_id)

    def test_func(self):
        review = self.get_object()
        return review.creator == self.request.user

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        search_query = keep_latest_page_param(self.request.GET.urlencode())
        context['search_query'] = escape(search_query)
        context['is_edited'] = True
        book_id = self.kwargs.get('book_id')
        context["book_id"] = book_id
        context["review_id"] = self.object.id
        return context

    def get_success_url(self):
        search_query = self.request.GET.urlencode()
        base_url = reverse('book_detail', kwargs={'pk': self.kwargs.get('book_id')})
        query_string = f"?{search_query}" if search_query else ""
        return f"{base_url}?{query_string}"

    def form_valid(self, form):
        review = form.save(commit=False)
        review.data_edited = timezone.now()
        review.save()
        messages.success(self.request, 'レビューが更新されました。')
        return super().form_valid(form)

reviews/templates/about.html
{% extends 'base.html' %}

{% block title %}About | {{ block.super }}{% endblock %}
{% block content %}
    <div class="px-6 py-24 sm:py-32 lg:px-8 max-w-2xl m-20 mx-auto">
    <div class="flex flex-col items-center justify-center">
    <svg xmlns="http://www.w3.org/2000/svg" width="100" height="100" fill="currentColor" class="bi bi-book" viewBox="0 0 16 16">
  <path d="M1 2.828c.885-.37 2.154-.769 3.388-.893 1.33-.134 2.458.063 3.112.752v9.746c-.935-.53-2.12-.603-3.213-.493-1.18.12-2.37.461-3.287.811V2.828zm7.5-.141c.654-.689 1.782-.886 3.112-.752 1.234.124 2.503.523 3.388.893v9.923c-.918-.35-2.107-.692-3.287-.81-1.094-.111-2.278-.039-3.213.492V2.687zM8 1.783C7.015.936 5.587.81 4.287.94c-1.514.153-3.042.672-3.994 1.105A.5.5 0 0 0 0 2.5v11a.5.5 0 0 0 .707.455c.882-.4 2.303-.881 3.68-1.02 1.409-.142 2.59.087 3.223.877a.5.5 0 0 0 .78 0c.633-.79 1.814-1.019 3.222-.877 1.378.139 2.8.62 3.681 1.02A.5.5 0 0 0 16 13.5v-11a.5.5 0 0 0-.293-.455c-.952-.433-2.48-.952-3.994-1.105C10.413.809 8.985.936 8 1.783z"/>
    </svg><p class="text-2xl font-bold tracking-tight text-gray-900">はじめまして</p>
    </div>
	<p class="mt-6 text-lg leading-8 text-gray-600">フリーランスのウェブプログラマーを目指している40代の佐藤博昭（さとう　ひろあき）と申します。30代に5年程プログラミングの勉強をしており、現在は再学習を始めてから約1年半が経ちました。現在は主にDjangoに取り組んでおり、このサイトもDjangoを使用して作成しました。使用経験のあるフレームワークには、Django, Rails, React, Vue, Tailwind等があります。
このサイトを作成した理由は、青空文庫の検索機能の使い勝手を改善したいと感じたからです。普段は小説はあまり読みませんが、技術書は洋書を中心に多く読んでいます。
皆様のお役に立てるサイトを目指して制作いたしました。不具合等がありましたら、お気軽にご連絡ください。
<br/>お問い合わせは、以下のメールアドレスまでお願いします。
    </p>
        <p><a id="email-link" class="text-blue-500 hover:underline"></a></p>
    <script>
        document.addEventListener("DOMContentLoaded", function() {
            var emailLink = document.getElementById('email-link');
            var emailAddress = 'hiroakisatou' + '@' + 'outlook.com';
            emailLink.href = 'mailto:' + emailAddress;
            emailLink.innerText = emailAddress;
        });
    </script>
    </div>
{% endblock %}

reviews/templates/detail_search.html
{% extends 'base.html' %}

{% block title %}詳細検索{% endblock %}
{% load tailwind_filters %}
{% block content %}
  <h1 class="text-2xl font-bold mt-4 ml-4">詳細検索</h1>
<form method="post" class="space-y-4 mx-2 md:mx-20 mt-4">
      <p>下記の検索欄のうち検索条件に含めたい項目だけを入力ください。</p>
    {% csrf_token %}
    <div class="grid grid-cols-1 md:grid-cols-2 gap-4">
        <div id="div_id_title" class="mb-3">
            <label for="id_title" class="block text-gray-700 text-sm font-bold mb-2">書籍名</label>
            <input type="text" name="title" class="textinput py-2 border px-4 leading-normal rounded-lg text-gray-700 appearance-none border-gray-300 w-full bg-white block focus:outline-none" id="id_title">
        </div>
        <div id="div_id_title_reading" class="mb-3">
            <label for="id_title_reading" class="block text-gray-700 text-sm font-bold mb-2">書籍名（ひらがな読み）</label>
            <input type="text" name="title_reading" class="textinput py-2 border px-4 leading-normal rounded-lg text-gray-700 appearance-none border-gray-300 w-full bg-white block focus:outline-none" id="id_title_reading">
        </div>
    </div>
    <div class="grid grid-cols-1 md:grid-cols-2 gap-4">
        <div id="div_id_author_last_name" class="mb-3">
            <label for="id_author_last_name" class="block text-gray-700 text-sm font-bold mb-2">著者の姓</label>
            <input type="text" name="author_last_name" class="textinput py-2 border px-4 leading-normal rounded-lg text-gray-700 appearance-none border-gray-300 w-full bg-white block focus:outline-none" id="id_author_last_name">
        </div>
        <div id="div_id_author_first_name" class="mb-3">
            <label for="id_author_first_name" class="block text-gray-700 text-sm font-bold mb-2">著者の名</label>
            <input type="text" name="author_first_name" class="textinput py-2 border px-4 leading-normal rounded-lg text-gray-700 appearance-none border-gray-300 w-full bg-white block focus:outline-none" id="id_author_first_name">
        </div>
    </div>
    <div class="grid grid-cols-1 md:grid-cols-2 gap-4">
        <div id="div_id_author_last_name_reading" class="mb-3">
            <label for="id_author_last_name_reading" class="block text-gray-700 text-sm font-bold mb-2">著者の姓（ひらがな読み）</label>
            <input type="text" name="author_last_name_reading" class="textinput py-2 border px-4 leading-normal rounded-lg text-gray-700 appearance-none border-gray-300 w-full bg-white block focus:outline-none" id="id_author_last_name_reading">
        </div>
        <div id="div_id_author_first_name_reading" class="mb-3">
            <label for="id_author_first_name_reading" class="block text-gray-700 text-sm font-bold mb-2">著者の名（ひらがな読み）</label>
            <input type="text" name="author_first_name_reading" class="textinput py-2 border px-4 leading-normal rounded-lg text-gray-700 appearance-none border-gray-300 w-full bg-white block focus:outline-none" id="id_author_first_name_reading">
        </div>
    </div>
    <div class="grid grid-cols-1 md:grid-cols-2 gap-4">
        <div id="div_id_translator_last_name" class="mb-3">
            <label for="id_translator_last_name" class="block text-gray-700 text-sm font-bold mb-2">翻訳者の姓</label>
            <input type="text" name="translator_last_name" class="textinput py-2 border px-4 leading-normal rounded-lg text-gray-700 appearance-none border-gray-300 w-full bg-white block focus:outline-none" id="id_translator_last_name">
        </div>
        <div id="div_id_translator_first_name" class="mb-3">
            <label for="id_translator_first_name" class="block text-gray-700 text-sm font-bold mb-2">翻訳者の名</label>
            <input type="text" name="translator_first_name" class="textinput py-2 border px-4 leading-normal rounded-lg text-gray-700 appearance-none border-gray-300 w-full bg-white block focus:outline-none" id="id_translator_first_name">
        </div>
    </div>
   <div class="grid grid-cols-1 md:grid-cols-2 gap-4">
        <div id="div_id_translator_last_name_reading" class="mb-3">
            <label for="id_translator_last_name_reading" class="block text-gray-700 text-sm font-bold mb-2">翻訳者の姓（ひらがな読み）</label>
            <input type="text" name="translator_last_name_reading" class="textinput py-2 border px-4 leading-normal rounded-lg text-gray-700 appearance-none border-gray-300 w-full bg-white block focus:outline-none" id="id_translator_last_name_reading">
        </div>
        <div id="div_id_translator_first_name_reading" class="mb-3">
            <label for="id_translator_first_name_reading" class="block text-gray-700 text-sm font-bold mb-2">翻訳者の名（ひらがな読み）</label>
            <input type="text" name="translator_first_name_reading" class="textinput py-2 border px-4 leading-normal rounded-lg text-gray-700 appearance-none border-gray-300 w-full bg-white block focus:outline-none" id="id_translator_first_name">
        </div>
    </div>
    <div id="div_id_character_usage" class="mb-3 w-32">
        <label for="id_character_usage" class="block text-gray-700 text-sm font-bold mb-2">仮名遣い</label>
        <div class="relative">
            <select class="bg-white focus:outline-none border border-gray-300 rounded-lg py-2 px-4 block w-full appearance-none leading-normal text-gray-700" name="character_usage" id="id_character_usage">
                <option value="" selected>---------</option>
                <option value="新字旧仮名">新字旧仮名</option>
                <option value="旧字旧仮名">旧字旧仮名</option>
                <option value="新字新仮名">新字新仮名</option>
            </select>
            <div class="pointer-events-none absolute inset-y-0 right-0 flex items-center px-2 text-gray-700">
                <svg class="fill-current h-4 w-4" xmlns="http://www.w3.org/2000/svg" viewBox="0 0 20 20">
                    <path d="M9.293 12.95l.707.707L15.657 8l-1.414-1.414L10 10.828 5.757 6.586 4.343 8z"/>
                </svg>
            </div>
        </div>
    </div>
    <div class="mb-3">
        <label for="id_is_children_book" class="block text-gray-700 text-sm font-bold mb-1">児童書</label>
        <input type="checkbox" name="is_children_book" class="checkbox" id="id_is_children_book">
    </div>

    <button type="submit" class="inline-flex items-center px-4 py-2 border border-transparent text-sm font-medium rounded-md shadow-sm text-white bg-indigo-600 hover:bg-indigo-700 focus:outline-none focus:ring-2 focus:ring-offset-2 focus:ring-indigo-500">検索</button>
</form>
{% endblock %}

reviews/templates/index.html
{% extends "base.html" %}

{% block title %}ホーム | {{ block.super }}{% endblock %}
{% load static %}
{% block content %}
   <div class="bg-local w-full h-auto mx-auto" style="background-image: url({% static 'sky.webp' %}); background-color: #049fb6

; background-repeat: no-repeat; background-position: right;">
            <h1 class="text-2xl md:text-4xl font-bold text-white m-20 drop-shadow-lg" style="line-height: 1.5;">
                    <span class="inline md:hidden">ようこそ、<br/>このサイトでは</span>
                    <span class="hidden md:inline">ようこそ、このサイトでは</span>
                    <br/>青空文庫の検索とレビューの投 稿が可能です。</h1>
    </div>
{% if show_success_dialog %}
<div id="success-dialog" class="fixed inset-0 flex items-center justify-center z-50">
    <div class="bg-white p-6 rounded-lg shadow-lg">
        <div class="text-center">
            <div class="mx-auto flex h-12 w-12 items-center justify-center rounded-full bg-green-100">
                <svg class="h-6 w-6 text-green-600" fill="none" viewBox="0 0 24 24" stroke-width="1.5" stroke="currentColor" aria-hidden="true">
                    <path stroke-linecap="round" stroke-linejoin="round" d="M4.5 12.75l6 6 9-13.5" />
                </svg>
            </div>
            <h3 class="text-lg leading-6 font-medium text-gray-900 mt-4">アカウント作成に成功しました</h3>
            <div class="mt-2">
                <p class="text-sm text-gray-500">ようこそ、{{ request.user.username }} さん！</p>
            </div>
        </div>
        <div class="mt-5 sm:mt-6 sm:grid sm:grid-flow-row-dense sm:grid-cols-1 sm:gap-3">
            <button type="button" class="inline-flex w-full justify-center rounded-md bg-indigo-600 px-3 py-2 text-sm font-semibold text-white shadow-sm hover:bg-indigo-500 sm:col-start-1" onclick="document.getElementById('success-dialog').style.display='none'">閉じる</button>
        </div>
    </div>
</div>
{% endif %}
    <div class="m-4 md:m-20">

        <div class="flex justify-center mb-8 mx-auto md:w-1/2">
            <div class="max-w-lg">
                <div class="flex flex-row gap-6 items-center">
                <h1 class="text-2xl font-bold mb-4 text-neutral-700">検索から始めよう</h1>
                <a href="{% url 'detail_search' %}" class="text-blue-600 hover:text-blue-800 hover:underline">詳細検索へ</a>
                </div>
                <form method="get" action="{% url 'search_result' %}">
                    <input type="text" name="q" class="w-64 border rounded px-3 py-2" placeholder="作品名、著者名で検索">
                    <button type="submit" class="bg-blue-500 text-white px-4 py-2 rounded mt-2">検索</button>
                </form>
            </div>
        </div>

            <div class="border-t border-neutral-400 mt-6">
                <h3 class="text-xl my-4 font-bold">サービスの特徴</h3>
            <ol class="list-decimal list-outside pl-10 text-neutral-700">
                <li class="mt-1">検索機能：青空文庫の書籍を簡単に検索できます。</li>
                <li class="mt-1">レビュー投稿：レビューの投稿には「サインアップ」を選んで登録する必要があります。</li>
                <li class="mt-1">ログイン：一度登録すると、次回からは「ログイン」を選択して情報を入力するだけでログインできます。</li>
                <li class="mt-1">レビュー編集：自分の投稿したレビューは後から編集が可能です。</li>
                <li class="mt-1">本の閲覧：本の閲覧は検索結果のURLリンクから青空文庫のサイトを開いて行えます。また、本の詳細情報の閲覧も青空文庫のリンクから可能です。</li>
                <li class="mt-1">レビューの閲覧:サイトへの登録なしで、どなたでも閲覧可能です。</li>
                <li class="mt-1">プロフィールの閲覧:サインアップすると、あなただけが見られるプロフィールページが作られます。そこで20件までの検索履歴やレビューを投稿した本を確かめることが出来ます。</li>

            </ol>
            </div>
            <div class="border-t border-neutral-400 mt-6">
                <h3 class="text-xl my-4 font-bold">ご利用方法</h3>
            <ol class="list-decimal list-outside pl-10 text-neutral-700">
                <li class="mt-1">登録：最初に「サインアップ」ボタンから登録してください。</li>
                <li class="mt-1">ログイン：次回からは「ログイン」ボタンからログインしてください。</li>
                <li class="mt-1">検索：検索ボックスに書籍名や著者名を入力して検索してください（ひらがなでの検索も可能です）。</li>
                <li class="mt-1">レビュー投稿：本の詳細ページからレビューを投稿できます。</li>
            </ol>
            </div>
            <div class="border-t border-neutral-400 mt-6 text-neutral-700">
                <h3 class="text-xl my-4 font-bold">利用上の注意</h3>
                <ul class="list-disc pl-5">
                    <li class="mt-1 text-sm">このサイトの検索データは2024年7月20日時点で青空文庫から入手可能なCSVファイルに基づきます。</li>
                    <li class="mt-1 text-sm">このサイトのジャンル表示は日本図書協会から入手出来るNDC９版のttlデータに青空文庫のデータを一致させて行っています。そのため、青空文庫の分野別項目名とは異なっております。</li>
                </ul>
            </div>
    </div>
{% endblock %}